{ inputs, ... }:
{
  perSystem =
    {
      config,
      lib,
      pkgs,
      system,
      ...
    }:
    let
      paperServer = inputs.nix-minecraft.legacyPackages.${system}.paperServers."paper-26_2-build_112";

      eula = pkgs.writeText "eula.txt" ''
        # Generated by the YRush Nix Paper runner.
        eula=true
      '';

      serverProperties = pkgs.writeText "server.properties" ''
        server-ip=127.0.0.1
        server-port=25565
        online-mode=false
        enforce-secure-profile=false
        level-name=yrush-normal-world
        level-seed=yrush-paper-26.2-development
        level-type=minecraft:normal
        spawn-protection=0
        view-distance=3
        simulation-distance=3
      '';

      pluginConfig =
        pkgs.runCommand "yrush-config.yml"
          {
            nativeBuildInputs = [
              pkgs.unzip
              pkgs.yq-go
            ];
          }
          ''
            unzip -p ${config.packages.yrush}/share/yrush/YRush.jar config.yml \
              | yq eval '.debug.enabled = true | .["bot-packets"].enabled = true' - \
              > "$out"
          '';

      paper = pkgs.writeShellApplication {
        name = "yrush-paper";
        runtimeInputs = [
          pkgs.coreutils
          pkgs.jdk25
        ];
        text = ''
          state_dir="''${YRUSH_PAPER_STATE_DIR:-$PWD/.yrush-paper}"
          mkdir -p "$state_dir/cache" "$state_dir/plugins/YRush"

          install -m 0644 ${eula} "$state_dir/eula.txt"
          install -m 0644 ${serverProperties} "$state_dir/server.properties"
          if [[ ! -e "$state_dir/plugins/YRush/config.yml" ]]; then
            install -m 0644 ${pluginConfig} "$state_dir/plugins/YRush/config.yml"
          fi
          install -m 0644 ${config.packages.yrush}/share/yrush/YRush.jar "$state_dir/plugins/YRush.jar"
          ln -sfn ${paperServer.vanillaJar} "$state_dir/cache/mojang_26.2.jar"

          cd "$state_dir"
          exec ${pkgs.jdk25}/bin/java -Xms512M -Xmx1G \
            -jar ${paperServer}/lib/minecraft/server.jar --nogui
        '';
      };
    in
    {
      _module.args.yrushPaper = {
        inherit paper;
      };

      apps.paper = {
        type = "app";
        program = lib.getExe paper;
        meta.description = "Run Paper 26.2 with YRush in .yrush-paper";
      };
    };
}
